name: Child Action 3

on: 
  workflow_dispatch:
    inputs:
      parametr_1:
        description: 'Some description'     
        required: true
        default: 'Default value'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, Child Action!

      - name: Echo 'parametr_1'
        run: |
          echo "Value of the 'parametr_1' is --> '"${{ github.event.inputs.parametr_1 }}"'"
