name: Child Action 4

on: 
  workflow_dispatch:
    inputs:
      parametr:
        description: 'Some description'     
        required: true
        default: 'Default value'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run the script Child GitHub Action
        run: echo Hello, Child Action!

      - name: Echo 'parametr' to check vakue
        run: |
          echo "Value of the 'parametr' is --> "${{ github.event.inputs.parametr }}""
          
      - name: Sleep
        run: sleep 60
